spring.application.name=chatapp

spring.datasource.url=jdbc:h2:file:./chatapp
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

jwt.secret=gJafYk4gVrg2oc2A2KcitdgwRjQJgI7uqR9lHD_mvjc
  