spring:
  application:
    name: chatapp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:h2:file:./chatapp
    username: sa
    password: 
jwt:
  secret: gJafYk4gVrg2oc2A2KcitdgwRjQJgI7uqR9lHD_mvjc
  