spring.application.name=chatapp

spring.datasource.url=jdbc:mariadb://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.orm.jdbc.extract=TRACE

jwt.secret=This is some secret key which is about 32 characters long